services:

  navidrome:
    image: deluan/navidrome:0.58.0
    container_name: navidrome
    environment:
      # Optional: put your config options customization here. Examples:
      - ND_ENABLESHARING=true
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=warn
      - ND_LASTFM_APIKEY=3d762689e2d3a9b405b50e9f52057cbd
      - ND_LASTFM_SECRET=614f32828e0e993f2296be0130c94c42
      #- ND_BASEURL=""
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/navidrome/data:/data
      - /mnt/pool/music:/music:ro
    ports:
      - 4533:4533
    labels:
      tsdproxy.enable: true
      tsdproxy.name: "navidrome"