services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7ubu2404-ls79
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=http://192.168.2.7 #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /data/jellyfin/library:/config
      - /data/jellyfin/tvshows:/data/tvshows
      - /data/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped
    labels:
      tsdproxy.enable: true
      tsdproxy.name: "jellyfin"