services:

  portainer:
    image: portainer/portainer-ce:2.33.2-alpine
    container_name: portainer
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
    restart: unless-stopped